language: java
jdk:
  - oraclejdk8

deploy:
  provider: releases
  api_key: "cdcf006cc549fe5bd0f3948e2cec716d700b2b21"
  file: "target/nuevavida-1.0-SNAPSHOT-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true
